version: '3.8'

services:
  ranker:
    build:
      context: .
      dockerfile: Dockerfile.perspective
    environment:
      - PERSPECTIVE_API_KEY=${PERSPECTIVE_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "perspective_ranker:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]