version: '3.8'

services:
  ranker:
    build:
      context: .
      dockerfile: Dockerfile.perspective
      args:
        - PERSPECTIVE_API_KEY=${PERSPECTIVE_API_KEY}
    image: perspective-ranker:latest
    environment:
      - PERSPECTIVE_API_KEY=${PERSPECTIVE_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "perspective_ranker:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  caller:
    build:
      context: .
      dockerfile: Dockerfile.perspective
      args:
        - PERSPECTIVE_API_KEY=${PERSPECTIVE_API_KEY}
    environment:
      - PERSPECTIVE_API_KEY=${PERSPECTIVE_API_KEY}
    volumes:
      - .:/app
    command: ["python", "caller.py"]
    depends_on:
      - ranker