[tool.poetry]
name = "ranking-challenge-perspective"
version = "0.1.0"
description = "Ranker based on Perspective API scores."
authors = ["Haroon Iftikhar <hiftikha@umich.edu>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.68.0"
uvicorn = "^0.15.0"
google-api-python-client = "^2.0.0"
python-dotenv = "^0.19.0"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"