name: Run pytest Tests

# These rules will run the workflow when a commit is pushed to the main branch, or a PR against the main branch is opened or updated
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This concurrency mode will cancel in-progress workflows if a new commit is pushed
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

# These are needed by some worker jobs. However, those are not currently tested, and
# even if they were, credentials should not be needed under test.
env:
  PERSPECTIVE_API_KEY: fake_api_key

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and run services, then run tests
        run: pytest
